language: r

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs
  on:
    branch: master

script:
  - Rscript --vanilla scripts/create_data.R
  - Rscript --vanilla scripts/render_rmd.R
